# Scrapers
scrape:
	python -m app.scrapers.blijdorp
	python -m app.scrapers.maarten
	python -m app.scrapers.vandevijver
	python -m app.scrapers.voorberg

base:
	python -m app.scrapers.base

blijdorp:
	python -m app.scrapers.blijdorp

kleef:
	python -m app.scrapers.vankleef

maarten:
	python -m app.scrapers.maarten

real:
	python -m app.scrapers.realworks

vijver:
	python -m app.scrapers.vandevijver

voorberg:
	python -m app.scrapers.voorberg

# FCM
broadcast:
	python -m app.broadcast