scrape:
	python -m app.scrapers.blijdorp
	python -m app.scrapers.maarten
	python -m app.scrapers.vandevijver

blijdorp:
	python -m app.scrapers.blijdorp

maarten:
	python -m app.scrapers.maarten

vijver:
	python -m app.scrapers.vandevijver
