# Scrapers
scrape:
	python -m app.scrapers.blijdorp
	python -m app.scrapers.maarten
	python -m app.scrapers.vandevijver
	python -m app.scrapers.vankleef
	python -m app.scrapers.voorberg

# Base scrapers
base:
	python -m app.scrapers.base

real:
	python -m app.scrapers.realworks

# Makelaars
blijdorp:
	python -m app.scrapers.blijdorp

de:
	python -m app.scrapers.de

kleef:
	python -m app.scrapers.vankleef

lokkerbol:
	python -m app.scrapers.lokkerbol

m1:
	python -m app.scrapers.m1

maarten:
	python -m app.scrapers.maarten

oosten:
	python -m app.scrapers.vanoosten

prins:
	python -m app.scrapers.prins

woonvisie:
	python -m app.scrapers.woonvisie

vijver:
	python -m app.scrapers.vandevijver

voorberg:
	python -m app.scrapers.voorberg

# FCM
broadcast:
	python -m app.broadcast